create share widget
reearth/plugin-example pull request #2
Opened 2022-04-28 09:02 UTC by nbayashi

## Changes proposed in this pull request
- Add 2  sample widget plugin

## Twitter share widget plugin
### Properties
- URL: Share URL you want
- Hashtags: Add a comma-separated list of hashtags to a Tweet using the hashtags parameter.
- Text: Default text in a Tweet.

<img width="452" alt="image" src="https://user-images.githubusercontent.com/13118515/165708932-6d2cdd83-b03d-4be9-bde2-72781fa48f51.png">

## Facebook share widget plugin
### Properties
- URL: Share URL you want
<img width="454" alt="image" src="https://user-images.githubusercontent.com/13118515/165710655-3b03d798-5bd2-426d-a594-737852c2198b.png">

## Remaining issues
I don't know why I have to re-checked widget toggle after set properties to refresh.

![タイトルなし](https://user-images.githubusercontent.com/13118515/165717130-85a94f0a-19f4-452b-84fa-816ce821c456.gif)

2022-04-28 09:22 UTC, rot1024 requested changes

2022-04-28 09:22 UTC, rot1024 commented on facebook-share-widget.js
> +      property: reearth.widget.property.default
```suggestion
      type: "facebook",
      property: reearth.widget.property.default
```

2022-04-28 09:22 UTC, rot1024 commented on facebook-share-widget.js
> +    if (e.source !== parent) return;
```suggestion
    if (e.source !== parent || !e.data || e.data.type !== "facebook") return;
```

fix Twitter widget also

2022-04-28 09:22 UTC, rot1024 commented on facebook-share-widget.js
> +// recieve message
```suggestion
	// recieve message
```

Indent

2022-04-28 09:55 UTC, nbayashi reviewed
fix some line

2022-04-28 10:16 UTC, nbayashi reviewed
submit

2022-08-31 02:25 UTC, rot1024 approved these changes

2022-08-31 02:25 UTC, merged